# Generated by Django 3.1.5 on 2021-05-24 10:56

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=40)),
                ('Name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=300)),
                ('phone_number', models.CharField(max_length=60)),
                ('home_Address', models.CharField(max_length=60)),
                ('home_Address_continued', models.CharField(max_length=60)),
                ('postcode', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cost_of_order', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('overall_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('original_pack', models.TextField(default='')),
                ('stripe_p_id', models.CharField(default='', max_length=300)),
                ('user_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size', models.CharField(blank=True, max_length=3, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lineitems', to='checkout.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
