# Generated by Django 3.1.5 on 2021-04-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost_of_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
