# Generated by Django 3.1.5 on 2021-04-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210425_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='grand_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='overall_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
