# Generated by Django 3.1.5 on 2021-04-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210425_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_pack',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_p_id',
            field=models.CharField(default='', max_length=300),
        ),
    ]
