# Generated by Django 3.1.5 on 2021-01-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='prices',
            field=models.DecimalField(
                decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
