# Generated by Django 3.1.5 on 2021-02-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210117_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shoe_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prices',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
